fruits=[]
user=input("enter a fruit name :")
fruits.append(user)
user=input("enter a fruit name :")
fruits.append(user)
user=input("enter a fruit name :")
fruits.append(user)
user=input("enter a fruit name :")
fruits.append(user)
user=input("enter a fruit name :")
fruits.append(user)
user=input("enter a fruit name :")
fruits.append(user)
user=input("enter a fruit name :")
fruits.append(user)
print(fruits)