marks=[]
user=int(input("enter the marks :"))
marks.append(user)
user=int(input("enter the marks :"))
marks.append(user)
user=int(input("enter the marks :"))
marks.append(user)
user=int(input("enter the marks :"))
marks.append(user)
user=int(input("enter the marks :"))
marks.append(user)
user=int(input("enter the marks :"))
marks.append(user)
marks.sort()
print(marks)